// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Keyword struct {
	ID      int32  `json:"id"`
	Keyword string `json:"keyword"`
	Active  bool   `json:"active"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

type UserMessage struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	KeywordID   sql.NullInt32  `json:"keyword_id"`
	Count       sql.NullInt32  `json:"count"`
	LastMessage sql.NullString `json:"last_message"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
